apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether-node.fullname" . }}
  labels:
    {{- include "aether-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "aether-node.selectorLabels" . | nindent 4 }}
